openapi: 3.0.1
info:
  title: Exemple simple API Task
  version: 1.0.0

paths:
  /tasks:
    get:
      summary: Retourne une liste de tâches
      responses:
        "200":
          description: Liste de tâches trouvées
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    title:
                      type: string
                      example: "Apprendre OpenAPI"
                    completed:
                      type: boolean
                      example: false
        "404":
          description: Aucune tâche trouvée
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Aucune tâche trouvée"
    post:
      summary: Crée une liste de nouvelles tâches
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                required:
                  - title
                properties:
                  title:
                    type: string
                    example: "Nouvelle tâche"
                  completed:
                    type: boolean
                    example: false
      responses:
        "201":
          description: Liste de tâches créée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    title:
                      type: string
                      example: "Nouvelle tâche"
                    completed:
                      type: boolean
                      example: false
        "400":
          description: Erreur - données de la requête invalides
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Données de la requête invalides"
    delete:
      summary: Supprime une liste de tâches
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: integer
              example:
                ids: [1, 2, 3]
      responses:
        "200":
          description: Liste de tâches supprimées
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    title:
                      type: string
                      example: "Ancienne tâche"
                    completed:
                      type: boolean
                      example: true
        "400":
          description: Erreur - liste d'IDs invalide
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Liste d'IDs invalide"

  /tasks/{id}:
    get:
      summary: Retourne une tâche par ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Tâche trouvée
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  title:
                    type: string
                    example: "Apprendre OpenAPI"
                  completed:
                    type: boolean
                    example: false
        "404":
          description: Tâche non trouvée
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Task not found"
    delete:
      summary: Supprime une tâche par ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Tâche supprimée
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  title:
                    type: string
                    example: "Apprendre OpenAPI"
                  completed:
                    type: boolean
                    example: false
        "404":
          description: Tâche non trouvée
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Task not found"
