openapi: 3.0.1
info:
  title: API Produits
  version: 1.0.0

paths:
  /products:
    get:
      summary: Recherche de produits
      parameters:
        - $ref: "#/components/parameters/LimitParam"
        - $ref: "#/components/parameters/QParam"
      responses:
        "200":
          description: Liste de produits trouvés
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
              examples:
                multipleProducts:
                  summary: Plusieurs produits trouvés
                  value:
                    - name: "Lait"
                      expiration_datetime: "2025-12-01T00:00:00Z"
                      price: 1.5
                    - name: "Pain"
                      expiration_datetime: "2025-09-15T00:00:00Z"
                      price: 0.8
                emptyList:
                  summary: Aucun produit trouvé
                  value: []

components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
          example: "Lait"
        expiration_datetime:
          type: string
          format: date-time
          example: "2025-12-01T00:00:00Z"
        price:
          type: number
          format: float
          example: 2.5

  parameters:
    LimitParam:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        example: 10
      description: Nombre maximum d’éléments à retourner
    QParam:
      name: q
      in: query
      required: false
      schema:
        type: string
        example: "lait"
      description: Terme de recherche
