openapi: 3.0.1
info:
  title: API Produits & Commandes
  version: 1.0.0

paths:
  /products:
    get:
      tags:
        - Products
      summary: Recherche de produits
      parameters:
        - $ref: "#/components/parameters/LimitParam"
        - $ref: "#/components/parameters/QParam"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"

  /orders:
    get:
      tags:
        - Orders
      summary: Liste paginée des commandes
      parameters:
        - $ref: "#/components/parameters/PageParam"
        - $ref: "#/components/parameters/SizeParam"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"

    post:
      tags:
        - Orders
      summary: Créer une commande (auth requise)
      security:
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        "201":
          description: Créé

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
        expiration_datetime:
          type: string
          format: date-time
        price:
          type: number
          format: float

    Order:
      type: object
      properties:
        identifier:
          type: integer
        customer_name:
          type: string
        creation_datetime:
          type: string
          format: date-time
        total_amount:
          type: number
          format: float

  parameters:
    LimitParam:
      name: limit
      in: query
      schema:
        type: integer
    QParam:
      name: q
      in: query
      schema:
        type: string
    PageParam:
      name: page
      in: query
      schema:
        type: integer
    SizeParam:
      name: size
      in: query
      schema:
        type: integer
